name: Integration build rmw_iceoryx

on:
  push:
    
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
          os: [ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Setup ROS
        uses: ros-tooling/setup-ros@foxy
        with:
          required-ros-distributions: foxy
      - name: Install Iceoryx Dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake libacl1-dev libncurses5-dev pkg-config
      - name: Build & Test
        uses: ros-tooling/action-ros-ci@foxy
        with:
          package-name: rmw_iceoryx_cpp iceoryx_ros2_bridge
          target-ros2-distro: foxy
          vcs-repo-file-url: |
            ./.github/workflows/additional_repos.repos
